server:
  port: 5503

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/erp
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5500/eureka

  instance:
    prefer-ip-address: true